### ISSUE TITLE
Add README.md

### ISSUE THREAD

**Issue by Evavic44** [Evavic44/The-Tree-Musketeers#1]
As explained on the description, this repo is for working on small web development projects and documenting my developer journey. `Newbies` and `Oldbies` 😄 can use this repo for inspiration or just plain fun. Contributions are highly appreciated.

- [x] Add a short `README`

**Comment by prathimacode-hub** [comment]
I would like to work on this issue. Can I? @Evavic44

**Comment by Evavic44** [comment]
Sure thing @prathimacode-hub 😎

**Comment by prathimacode-hub** [comment]
I had created a PR for the same. Kindly look in it and let me know if any changes required. @Evavic44

**Comment by Evavic44** [comment]
It's awesome. Thank you.

**Comment by prathimacode-hub** [comment]
You're welcome. Thanks for giving my this opportunity to collaborate. That was really fun to do. 🙌😀@Evavic44

**Comment by Evavic44** [comment]
I have an idea, Will it be possible to change the `Project Admin` section to a `contributors section`, so people that contributes to the projects can add their profile?

**Comment by prathimacode-hub** [comment]
Yes, sure. That can be done. But not any had contributed yet. If we do add up, it might look empty. If it's of no problem then I can replace project admin with contributors section @Evavic44

**Comment by Evavic44** [comment]
You have contributed, so you can add your profile if you want.

**Comment by prathimacode-hub** [comment]
Yup, I will update. Should i remove project admin? @Evavic44

**Comment by Evavic44** [comment]
Yes.

**Comment by prathimacode-hub** [comment]
Yup, it's done. Check up with the PR. @Evavic44
