### ISSUE TITLE
Add a projects section

### ISSUE THREAD

**Issue by Evavic44** [Evavic44/The-Tree-Musketeers#5]
In the README, add a projects section where screenshot of each projects will be shown.
Images should be resized to not take up too much space in the README.

Project Screenshot 👇🏾 

#### `CSS Cards`
<img src="https://user-images.githubusercontent.com/62628408/117551074-bfa8c580-b03b-11eb-8cbd-5f1550d4d3d8.png" width="400px">

#### `CSS Image Preview Card`
<img src="https://user-images.githubusercontent.com/62628408/117550988-30031700-b03b-11eb-8f7b-7ecd6e4d16ec.png" width="400px">

**Comment by divyanshu887** [comment]
I would like to work on this issue. Can I? @Evavic44

**Comment by Evavic44** [comment]
> I would like to work on this issue. Can I? @Evavic44

Sure, go ahead.

**Comment by Evavic44** [comment]
LGTM! You can add your profile to the contributors section at the bottom if you want. 👍🏾
