### ISSUE TITLE
Add contribution guidelines 

### ISSUE THREAD

**Issue by Evavic44** [Evavic44/The-Tree-Musketeers#8]
- [x] Add contribution guideline
- [x] Change the `Contribution guideline` link in [README.md](https://github.com/Evavic44/The-Tree-Musketeers#readme) to the newly created contribution guideline link.

**Comment by prathimacode-hub** [comment]
Is this open for contribution? @Evavic44

**Comment by Evavic44** [comment]
> Is this open for contribution? @Evavic44 

Hello Prathima, how have you been. 👋🏾 Sure it is open. I'll assign you to it.

**Comment by prathimacode-hub** [comment]
I'm doing great, thanks for asking. Hope you're doing fine as well.  Sure, thanks. @Evavic44

**Comment by prathimacode-hub** [comment]
I have opened up a PR #9. Can you check it out and do notify if anything else is needed from my end. @Evavic44

**Comment by Evavic44** [comment]
> I have opened up a PR #9. Can you check it out and do notify if anything else is needed from my end. @Evavic44

Okay doing that now. Thanks.
